name: CI_Pipeline

on:
  push:
    branches:
      - prod

  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean old dependencies
        run: |
          rm -rf node_modules package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Give permission to vite
        run: chmod +x node_modules/.bin/vite

      - name: Build Project
        run: npm run build
